import { Menu } from './menu.model';
 
export const verticalMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics',null, 'public', null, true, 0, "white"),
    new Menu(2, 'Property', '/sare/property', null, 'assignment', null, true, 0, "white"),
    new Menu(3, 'Realtors', '/sare/realtors', null, 'gradient', null, true, 0, "white"),
    new Menu(4, 'Marketing', '/sare/marketing', null, 'device_hub', null, true, 0, "white"),
    new Menu(5, 'Sales','/sare/sales', null, 'business_center', null, true, 0, "white"),
    new Menu(6, 'Manage Lead','/sare/managelead', null, 'schedule', null, true, 0, "white"),
    new Menu(7, 'Payment Schedule','/sare/paymentschedule', null, 'list_alt', null, false, 0, "white"),
    new Menu(8, 'Builder','/sare/alert', null, 'collections', null, false, 0, "white"),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'forum', null, false, 1, "white"),
   
    new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
    
    
    
    // new Menu(19, 'Cancelled Claims','/sare/billing/cancelledClaims', null, 'cancel', null, false, 3, "white"),
    // new Menu(13, 'Incoming Orders', '/sare/analytics/incomingorders', null, 'filter_none', null, true, 1, "white"),
    // new Menu(14, 'Completed Appointments', '/sare/reports/completedAppointments', null, 'arrow_back', null, false, 4, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
    new Menu(19, 'Leads', '/sare/marketing/lead', null, 'group', null, true, 4, "white"),
    new Menu(20, 'Campaigns','/sare/marketing/campaigns', null, 'assessment', null, true, 4, "white"),
    // new Menu(21, 'Contacts','/sare/marketing/contacts', null, 'schedule', null, false, 4, "white"),
    new Menu(21, 'Prospects','/sare/marketing/prospect', null, 'outlined_flag', null, false, 4, "white"),
    new Menu(22, 'Campaign  Dashboard','/sare/marketing/campaignPerformance', null, 'dashboard', null, true, 4, "white"),
    new Menu(23, 'Customer','/sare/sales/customer', null, 'group_add', null, false, 5, "white"),
    new Menu(24, 'Deals','/sare/sales/deals', null, 'confirmation_number', null, false, 5, "white"),
    // new Menu(19, 'Itemised Statements', '/sare/reports/itemisedStatements', null, 'post_add', null, true, 4, "lightskyblue"),
    // new Menu(12, 'Ageing Analysis','/sare/billing/ageinganalysis', null, 'assessment', null, false, 3, "lightskyblue"),
    // new Menu(11, 'Manage Schedules','/sare/patients/manageschedules', null, 'schedule', null, false, 2, "white"),
    // new Menu(45, 'Appointments','/sare/patients/appointments', null, 'schedule', null, true, 2, "lightskyblue"),
    // Wanted page new Menu(41, 'Visit Records','/sare/patients/patientvisitrecords', null, 'confirmation_number', null, false, 2, "white"),
    // new Menu(12, 'Confirm Appointments','/sare/patients/confirmappointments', null, 'confirmation_number', null, false, 2, "white"),
    // new Menu(13, 'Assign Physicians','/sare/patients/assignphysicians', null, 'assignment_turned_in', null, false, 2, "white"),
    // new Menu(14, 'Text Log','/sare/patients/textlog', null, 'message', null, false, 2, "lightskyblue"),
    // new Menu(24, 'Create Claims',null, null, 'note_add', null, true, 3, "lightskyblue"),
    // new Menu(16, 'Attorneys', '/sare/admin/attorneys', null, 'record_voice_over', null, false, 5, "lightskyblue"),
    // new Menu(18, 'Internal Physicians', '/sare/admin/iphysicians', null, 'person', null, false, 5, "lightskyblue"),
    // new Menu(20, 'CPT Codes', '/sare/admin/cptcodes', null, 'perm_identity', null, false, 5, "lightskyblue"),
    // new Menu(17, 'ICD Codes', '/sare/admin/icdcodes', null, 'perm_identity', null, false, 5, "lightskyblue"),
    // new Menu(48, 'Lookup Options', '/sare/admin/lookups', null, 'zoom_in', null, false, 5, "lightskyblue"),
    // new Menu(21, 'Pharmacies', '/sare/admin/pharmacies', null, 'insert_chart_outlined', null, false, 5, "white"),
    // new Menu(22, 'Referring Physicians', '/sare/admin/referringphysicians', null, 'face', null, false, 5, "lightskyblue"),
    // new Menu(23, 'Imaging Partners', '/sare/admin/imagingpartners', null, 'image_search', null, false, 5, "white"),
    // new Menu(46, 'Settings', '/sare/admin/settings', null, 'settings', null, false, 5, "lightskyblue"),
    // new Menu(47, 'Error Log', '/sare/admin/errorLog', null, 'error', null, false, 5, "lightskyblue"),
    // new Menu(29, 'Text Templates', '/sare/admin/texttemplates', null, 'forum', null, false, 5, "lightskyblue"),
    // new Menu(30, 'Email Templates', '/sare/admin/emailtemplates', null, 'email', null, false, 5, "lightskyblue"),
    // new Menu(31, 'Event Log', '/sare/admin/eventlog', null, 'bookmark', null, false, 5, "lightskyblue"),
    // new Menu(51, 'Referring Physicians', '/sare/reports/referringPhysicians', null, 'filter_none', null, false, 4, "orange"),
    // new Menu(52, 'Attorneys', '/sare/reports/attorneys', null, 'filter_none', null, false, 4, "orange"),
    // new Menu(34, 'Patient Status', '/sare/reports/patientstatus', null, 'accessible_forward', null, false, 4, "orange"),
    // new Menu(35, 'Lost Sales Report', '/sare/reports/lostsalesreport', null, 'assignment', null, false, 4, "orange"),
    // new Menu(36, 'Billing Status', '/sare/reports/billingstatus', null, 'forum', null, false, 4, "orange"),
    // new Menu(37, 'Incoming Referral', '/sare/reports/incomingreferral', null, 'arrow_forward', null, false, 4, "orange"),
]

export const brokerMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics', null, 'public', null, true, 0, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
    //  new Menu(5, 'Sales','/sare/sales', null, 'business_center', null, true, 0, "white"),
    // new Menu(2, 'Property', '/sare/property', null, 'device_hub', null, true, 0, "white"),
    // new Menu(6, 'Broker/Agent', '/sare/broker', null, 'group_add', null, true, 0, "white"),
    new Menu(4, 'Marketing', '/sare/marketing', null, 'assignment', null, true, 0, "white"),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    // new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    // new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
    // new Menu(23, 'Customer','/sare/sales/customer', null, 'group_add', null, false, 5, "white"),
    // new Menu(24, 'Deals','/sare/sales/deals', null, 'confirmation_number', null, false, 5, "white"),
    new Menu(19, 'Leads', '/sare/marketing/lead', null, 'group', null, true, 4, "white"),
    new Menu(20, 'Campaigns','/sare/marketing/campaigns', null, 'assessment', null, true, 4, "white"),
    // new Menu(21, 'Contacts','/sare/marketing/contacts', null, 'schedule', null, false, 4, "white"),
    new Menu(21, 'Prospects','/sare/marketing/prospect', null, 'outlined_flag', null, false, 4, "white"),
    new Menu(22, 'Campaign  Dashboard','/sare/marketing/campaignPerformance', null, 'dashboard', null, true, 4, "white"),
]

export const agentMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics', null, 'public', null, true, 0, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
     new Menu(5, 'Sales','/sare/sales', null, 'business_center', null, true, 0, "white"),
    new Menu(2, 'Property', '/sare/property', null, 'device_hub', null, true, 0, "white"),
    // new Menu(6, 'Broker/Agent', '/sare/broker', null, 'group_add', null, true, 0, "white"),
    new Menu(4, 'Marketing', '/sare/marketing', null, 'assignment', null, true, 0, "white"),
    new Menu(25,'Payments', '/sare/payments', null, 'monetization_on',null, true, 0, 'white'),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
    new Menu(23, 'Customer','/sare/sales/customer', null, 'group_add', null, false, 5, "white"),
    new Menu(24, 'Deals','/sare/sales/deals', null, 'confirmation_number', null, false, 5, "white"),
    new Menu(19, 'Leads', '/sare/marketing/lead', null, 'group', null, true, 4, "white"),
    new Menu(20, 'Campaigns','/sare/marketing/campaigns', null, 'assessment', null, true, 4, "white"),
    // new Menu(21, 'Contacts','/sare/marketing/contacts', null, 'schedule', null, false, 4, "white"),
    new Menu(21, 'Prospects','/sare/marketing/prospect', null, 'outlined_flag', null, false, 4, "white"),
    new Menu(22, 'Campaign  Dashboard','/sare/marketing/campaignPerformance', null, 'dashboard', null, true, 4, "white"),
]

export const builderMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics', null, 'public', null, true, 0, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'dashboard', null, false, 1, "white"),
   
    new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
    new Menu(2, 'Property', '/sare/property', null, 'device_hub', null, true, 0, "white"),
    new Menu(3, 'Realtors', '/sare/realtors', null, 'public', null, true, 0, "white"),
    // new Menu(4, 'Marketing', '/sare/marketing', null, 'assignment', null, true, 0, "white"),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
]

export const customerMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics', null, 'public', null, true, 0, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(2, 'Property', '/sare/property', null, 'device_hub', null, true, 0, "white"),
    new Menu(7, 'Payment Schedule','/sare/paymentschedule', null, 'monetization_on', null, false, 0, "white"),
    // new Menu(8, 'Alert','/sare/alert', null, 'collections', null, false, 0, "white"),
    new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
]
// export const passwordMenuItems = [
//     new Menu(1, 'Analytics', '/sare/analytics', null, 'public', null, true, 0, "white"),
//     new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
//     new Menu(4, 'Leads', '/sare/leads', null, 'assignment', null, true, 0, "white"),
//     new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'dashboard', null, false, 1, "white"),
//     new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
// ]
export const realtorMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics', null, 'public', null, true, 0, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'dashboard', null, false, 1, "white"),
    new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
     new Menu(5, 'Sales','/sare/sales', null, 'business_center', null, true, 0, "white"),
    new Menu(2, 'Property', '/sare/property', null, 'device_hub', null, true, 0, "white"),
    new Menu(6, 'Broker/Agent', '/sare/broker', null, 'group_add', null, true, 0, "white"),
    new Menu(4, 'Marketing', '/sare/marketing', null, 'assignment', null, true, 0, "white"),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
    new Menu(23, 'Customer','/sare/sales/customer', null, 'group_add', null, false, 5, "white"),
    new Menu(24, 'Deals','/sare/sales/deals', null, 'confirmation_number', null, false, 5, "white"),
    new Menu(19, 'Leads', '/sare/marketing/lead', null, 'group', null, true, 4, "white"),
    new Menu(20, 'Campaigns','/sare/marketing/campaigns', null, 'assessment', null, true, 4, "white"),
    // new Menu(21, 'Contacts','/sare/marketing/contacts', null, 'schedule', null, false, 4, "white"),
    new Menu(21, 'Prospects','/sare/marketing/prospect', null, 'outlined_flag', null, false, 4, "white"),
    new Menu(22, 'Campaign  Dashboard','/sare/marketing/campaignPerformance', null, 'dashboard', null, true, 4, "white"),
]

export const horizontalMenuItems = [
    new Menu(1, 'Analytics', '/sare/analytics',null, 'public', null, true, 0, "white"),
    // new Menu(2, 'Property', '/sare/property', null, 'assignment', null, true, 0, "white"),
    new Menu(3, 'Realtors', '/sare/realtors', null, 'gradient', null, true, 0, "white"),
    // new Menu(4, 'Marketing', '/sare/marketing', null, 'device_hub', null, true, 0, "white"),
    // new Menu(5, 'Sales','/sare/sales', null, 'business_center', null, true, 0, "white"),
    // new Menu(6, 'Manage Lead','/sare/managelead', null, 'schedule', null, true, 0, "white"),
    // new Menu(7, 'Payment Schedule','/sare/paymentschedule', null, 'list_alt', null, false, 0, "white"),
    new Menu(8, 'Builder','/sare/builder', null, 'collections', null, false, 0, "white"),
    new Menu(9, 'Settings', '/sare/admin', null, 'person', null, true, 0, "white"),
    // new Menu(10, 'Portfolio','/sare/property/portfolio', null, 'filter_none', null, false, 2, "white"),
    // new Menu(11, 'Inventory','/sare/property/inventory', null, 'accessible_forward', null, false, 2, "white"),
    new Menu(12, 'Dashboard', '/sare/analytics/dashboard', null, 'dashboard', null, false, 1, "white"),
    // new Menu(13, 'Lead Dashboard','/sare/analytics/leadgenerationdashboard', null, 'forum', null, false, 1, "white"),
   
    // new Menu(14, 'Sales Dashboard','/sare/analytics/SalesDashboard', null, 'arrow_downward', null, false, 1, "white"),
    
    
    
    // new Menu(19, 'Cancelled Claims','/sare/billing/cancelledClaims', null, 'cancel', null, false, 3, "white"),
    // new Menu(13, 'Incoming Orders', '/sare/analytics/incomingorders', null, 'filter_none', null, true, 1, "white"),
    // new Menu(14, 'Completed Appointments', '/sare/reports/completedAppointments', null, 'arrow_back', null, false, 4, "white"),
    new Menu(15, 'Permissions', '/sare/admin/permissions', null, 'fingerprint', null, false, 9, "white"),
    new Menu(16, 'Users', '/sare/admin/users', null, 'group_add', null, false, 9, "white"),
    new Menu(17, 'Role', '/sare/admin/role', null, 'gradient', null, true, 9, "white"),
    new Menu(18, 'Lead Status/Kanban', '/sare/admin/kanban', null, 'swap_horiz', null, true, 9, "white"),
    new Menu(19, 'Leads', '/sare/marketing/lead', null, 'group', null, true, 4, "white"),
    new Menu(20, 'Campaigns','/sare/marketing/campaigns', null, 'assessment', null, true, 4, "white"),
    // new Menu(21, 'Contacts','/sare/marketing/contacts', null, 'schedule', null, false, 4, "white"),
    new Menu(21, 'Prospects','/sare/marketing/prospect', null, 'outlined_flag', null, false, 4, "white"),
    new Menu(22, 'Campaign  Dashboard','/sare/marketing/campaignPerformance', null, 'dashboard', null, true, 4, "white"),
    new Menu(23, 'Customer','/sare/sales/customer', null, 'group_add', null, false, 5, "white"),
    new Menu(24, 'Deals','/sare/sales/deals', null, 'confirmation_number', null, false, 5, "white"),
    // new Menu(25, 'Campaign Performance Dashboard','/sare/marketing/campaignperformance', null, 'assignment_turned_in', null, false, 20, "white"),
    // new Menu(14, 'Text Log','/sare/patients/textlog', null, 'message', null, false, 2, "lightskyblue"),
    // new Menu(24, 'Create Claims',null, null, 'note_add', null, true, 3, "lightskyblue"),
    // new Menu(16, 'Attorneys', '/sare/admin/attorneys', null, 'record_voice_over', null, false, 5, "lightskyblue"),
    // new Menu(18, 'Internal Physicians', '/sare/admin/iphysicians', null, 'person', null, false, 5, "lightskyblue"),
    // new Menu(20, 'CPT Codes', '/sare/admin/cptcodes', null, 'perm_identity', null, false, 5, "lightskyblue"),
    // new Menu(17, 'ICD Codes', '/sare/admin/icdcodes', null, 'perm_identity', null, false, 5, "lightskyblue"),
    // new Menu(48, 'Lookup Options', '/sare/admin/lookups', null, 'zoom_in', null, false, 5, "lightskyblue"),
    // new Menu(21, 'Pharmacies', '/sare/admin/pharmacies', null, 'insert_chart_outlined', null, false, 5, "white"),
    // new Menu(22, 'Referring Physicians', '/sare/admin/referringphysicians', null, 'face', null, false, 5, "lightskyblue"),
    // new Menu(23, 'Imaging Partners', '/sare/admin/imagingpartners', null, 'image_search', null, false, 5, "white"),
    // new Menu(46, 'Settings', '/sare/admin/settings', null, 'settings', null, false, 5, "lightskyblue"),
    // new Menu(47, 'Error Log', '/sare/admin/errorLog', null, 'error', null, false, 5, "lightskyblue"),
    // new Menu(29, 'Text Templates', '/sare/admin/texttemplates', null, 'forum', null, false, 5, "lightskyblue"),
    // new Menu(30, 'Email Templates', '/sare/admin/emailtemplates', null, 'email', null, false, 5, "lightskyblue"),
    // new Menu(31, 'Event Log', '/sare/admin/eventlog', null, 'bookmark', null, false, 5, "lightskyblue"),
    // new Menu(51, 'Referring Physicians', '/sare/reports/referringPhysicians', null, 'filter_none', null, false, 4, "orange"),
    // new Menu(52, 'Attorneys', '/sare/reports/attorneys', null, 'filter_none', null, false, 4, "orange"),
    // new Menu(34, 'Patient Status', '/sare/reports/patientstatus', null, 'accessible_forward', null, false, 4, "orange"),
    // new Menu(35, 'Lost Sales Report', '/sare/reports/lostsalesreport', null, 'assignment', null, false, 4, "orange"),
    // new Menu(36, 'Billing Status', '/sare/reports/billingstatus', null, 'forum', null, false, 4, "orange"),
    // new Menu(37, 'Incoming Referral', '/sare/reports/incomingreferral', null, 'arrow_forward', null, false, 4, "orange"),
]
